### ISSUE TITLE
Already downloaded files are downloaded again.

### ISSUE THREAD

**Issue by optio50** [rafaelbiriba/my-local-putio#3]
Already downloaded files are downloaded again.
Is there an option to activate the not download again?
I see this is one of the abilities of the script.

**Comment by rafaelbiriba** [comment]
good catch... This is indeed a missing feature, for when the delete files is false!
I will try to pop with a solution for this, but I will only have time at the end of the month.

**Comment by rafaelbiriba** [comment]
@optio50 I fixed the bug on version v4.3.1!
Thanks for reporting here!
